name: Format Code (Manual Run)

on:
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - run: pip install black isort

    - run: |
        isort .
        black .
